# Generated by Django 2.2.3 on 2019-08-13 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0056_remove_item_cart'),
        ('users', '0004_remove_cart_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='item',
            field=models.ManyToManyField(blank=True, to='orders.Item'),
        ),
    ]
