# Generated by Django 2.2.3 on 2019-07-23 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pasta_Types',
            new_name='Dinner_Platter_Type',
        ),
        migrations.RenameModel(
            old_name='Pizza_Toppings',
            new_name='Pasta_Type',
        ),
        migrations.RenameModel(
            old_name='Pizza_Types',
            new_name='Pizza_Topping',
        ),
        migrations.RenameModel(
            old_name='Dinner_Platter_Types',
            new_name='Pizza_Type',
        ),
        migrations.RenameModel(
            old_name='Salad_Types',
            new_name='Salad_Type',
        ),
        migrations.RenameModel(
            old_name='Sizes',
            new_name='Size',
        ),
        migrations.RenameModel(
            old_name='Sub_Additions',
            new_name='Sub_Addition',
        ),
        migrations.RenameModel(
            old_name='Sub_Types',
            new_name='Sub_Type',
        ),
        migrations.RenameField(
            model_name='pasta_type',
            old_name='topping',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='pizza_topping',
            old_name='type',
            new_name='topping',
        ),
    ]
