# Generated by Django 2.2.3 on 2019-07-23 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20190723_1300'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dinner_Platter_Type',
        ),
        migrations.DeleteModel(
            name='Pasta_Type',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='type',
        ),
        migrations.DeleteModel(
            name='Salad_Type',
        ),
        migrations.DeleteModel(
            name='Sub_Addition',
        ),
        migrations.DeleteModel(
            name='Sub_Type',
        ),
        migrations.DeleteModel(
            name='Pizza',
        ),
        migrations.DeleteModel(
            name='Pizza_Topping',
        ),
        migrations.DeleteModel(
            name='Pizza_Type',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
