# Generated by Django 2.2.3 on 2019-07-23 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190723_1355'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
