# Generated by Django 2.2.3 on 2019-07-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_delete_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('pizzaType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_pricing', to='orders.Pizza')),
            ],
        ),
    ]
