# Generated by Django 2.2.3 on 2019-07-23 14:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_type', to='orders.Meal_Type')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_size', to='orders.Size')),
            ],
        ),
    ]
