# Generated by Django 2.2.3 on 2019-07-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190723_1432'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
