# Generated by Django 2.2.3 on 2019-07-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_delete_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
    ]
