# Generated by Django 2.2.3 on 2019-07-24 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dinner_platter_type',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='meal_type',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pasta_type',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pizza',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='pizza_type',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='salad_type',
            old_name='type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='sub_type',
            old_name='type',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='meal_size',
        ),
        migrations.AddField(
            model_name='order',
            name='pizza_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pizza_type1', to='orders.Pizza_Type'),
        ),
        migrations.AddField(
            model_name='pizza_type',
            name='meal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Meal_Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_type', to='orders.Meal_Type'),
        ),
    ]
