# Generated by Django 2.2.3 on 2019-07-24 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20190724_1457'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='order',
            name='pizza_type',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meal_type1', to='orders.Meal_Type'),
        ),
        migrations.DeleteModel(
            name='Pizza_Type',
        ),
        migrations.AddField(
            model_name='meal_type',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Meal'),
        ),
        migrations.AddField(
            model_name='order',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal', to='orders.Meal'),
        ),
    ]
