# Generated by Django 2.2.3 on 2019-07-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20190725_1346'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dinner_Platter_Type',
        ),
        migrations.DeleteModel(
            name='Pasta_Type',
        ),
        migrations.DeleteModel(
            name='Salad_Type',
        ),
        migrations.DeleteModel(
            name='Sub_Type',
        ),
        migrations.AlterField(
            model_name='order',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=models.SET('Item no longer exists'), to='orders.Meal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal_type',
            field=models.ForeignKey(null=True, on_delete=models.SET('Item no longer exists'), to='orders.Meal_Type'),
        ),
    ]
