# Generated by Django 2.2.3 on 2019-07-25 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_size_meal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='meal',
        ),
        migrations.AddField(
            model_name='meal_type',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
    ]
