# Generated by Django 2.2.3 on 2019-07-25 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_auto_20190725_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='meal',
        ),
        migrations.AddField(
            model_name='size',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Meal'),
        ),
    ]
