# Generated by Django 2.2.3 on 2019-07-26 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20190726_0916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_type',
            name='meal_addition',
            field=models.ManyToManyField(null=True, to='orders.Meal_Addition'),
        ),
    ]
