# Generated by Django 2.2.3 on 2019-07-26 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20190726_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal_type',
            name='meal_addition',
            field=models.ManyToManyField(blank=True, to='orders.Meal_Addition'),
        ),
    ]
