# Generated by Django 2.2.3 on 2019-07-26 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20190726_0920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal_addition',
            name='meal',
        ),
    ]
