# Generated by Django 2.2.3 on 2019-07-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_remove_meal_addition_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_type',
            name='size',
            field=models.ManyToManyField(to='orders.Size'),
        ),
    ]
