# Generated by Django 2.2.3 on 2019-07-26 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_meal_type_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='meal',
        ),
    ]
