# Generated by Django 2.2.3 on 2019-07-26 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0037_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='meal_type',
        ),
        migrations.AddField(
            model_name='price',
            name='meal_type',
            field=models.ManyToManyField(to='orders.Meal_Type'),
        ),
    ]
