# Generated by Django 2.2.3 on 2019-07-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_meal_addition_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_addition',
            name='meal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Meal'),
        ),
    ]
