# Generated by Django 2.2.3 on 2019-07-30 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_meal_addition_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal_type',
            name='topping',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
