# Generated by Django 2.2.3 on 2019-07-30 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_meal_type_topping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal_type',
            name='topping',
        ),
    ]
