# Generated by Django 2.2.3 on 2019-08-08 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_auto_20190808_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Meal'),
        ),
        migrations.AlterField(
            model_name='order',
            name='meal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Meal_Type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
    ]
