# Generated by Django 2.2.3 on 2019-08-08 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_auto_20190808_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='author',
            new_name='user',
        ),
    ]
