# Generated by Django 2.2.3 on 2019-08-13 09:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0052_order_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='Item',
        ),
    ]
