# Generated by Django 2.2.3 on 2019-08-13 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_cart_item'),
        ('orders', '0053_auto_20190813_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Cart'),
        ),
    ]
