# Generated by Django 2.2.3 on 2019-08-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_auto_20190813_1038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart',
        ),
    ]
